apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: time-app
  namespace: time-app
spec:
  values:
    image:
      repository: mpetrovic992/time-app # {"$imagepolicy": "flux-system:time-app:name"}
      image: v1.0.5 # {"$imagepolicy": "flux-system:time-app:tag"}
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        #         kubernetes.io/tls-acme: "true"
      hosts:
        - host: time-app.asg15.casual-trading.com
          paths:
            - path: /
      tls:
        - secretName: what-time-is-it-tls
          hosts:
            - time-app.asg15.casual-trading.com
