---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: time-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/apps/time-app/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

