apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: time-app
spec:
  interval: 60m
  chart:
    spec:
      kind: GitRepository
      name: bux
      namespace: flux-system


