---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./gitops/operators/cert-manager/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

